Split the dataset into a train (90% of the data) and a test set (10%) and train a
logistic regression classifier considering the tf.idf representation of the 3-grams
(of characters). What is its accuracy?

In [2]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, HashingVectorizer
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("lid201-medium.tsv",
                  sep="\t", 
                  usecols=[0, 1], 
                  names=["content", "label"])
#df = df.sample(10_000)

9593760

In [10]:
df.sample(5)

                                                  content     label
256577  میل درد بسیار ضعیف شده بود، امّا آسوده خاطر شد...  pes_Arab
725901  Todavia, foi apresentada em meu nome uma fórmu...  por_Latn
196434  Bushe Abena Kristu ba kubalilapo balefumya kwi...  bem_Latn
649307  Біблія каже: "Батьки... виховуйте їх [дітей] у...  ukr_Cyrl
432966                           Tana, Manguha Tag Uhong!  ceb_Latn

In [11]:
train, test = train_test_split(df, train_size=0.9)
train[0:5]

                                                  content     label
907508     沙說 ： 「 我的態度是積極的、嚴肅的、理性的，一些觀點雖然尖銳，用詞雖然激烈，卻是善意的。  zho_Hant
425941  Создание должности сотрудника по административ...  rus_Cyrl
847705  Као када одете код лекара, па он каже да имате...  srp_Cyrl
426818  Grenville Clark dan hadirin konferens Dublin y...  zsm_Latn
658339  Komisia rozhodnutím 2008 / 577 / ES [6] uveden...  slk_Latn

In [ ]:

vectorizer = TfidfVectorizer(analyzer="char", ngram_range=(3,3))
model = LogisticRegression()

X_train = vectorizer.fit_transform(train["content"])
Y_train = train["label"]

X_test = vectorizer.transform(test["content"])
Y_test = test["label"]

model.fit(X_train, Y_train)

Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)

train_acc = accuracy_score(Y_train, Y_train_pred)
test_acc = accuracy_score(Y_test, Y_test_pred)

print(f"Train accuracy: {train_acc:.3f}")
print(f"Test accuracy: {test_acc:.3f}")

KeyboardInterrupt